import React, {useState} from 'react';
const H = [{id:'small',title:'Small Hamper',price:'₹475',img:'/src/assets/small.webp'},{id:'medium',title:'Medium Hamper',price:'₹800',img:'/src/assets/medium.webp'},{id:'large',title:'Large Hamper',price:'₹1350',img:'/src/assets/large.webp'}];
function Modal({open,onClose,hamper,onOrder, onEnquiry}){if(!open)return null;return (<div style={{position:'fixed',inset:0,background:'rgba(0,0,0,0.6)',display:'flex',alignItems:'center',justifyContent:'center',zIndex:60}} onClick={onClose}><div onClick={e=>e.stopPropagation()} style={{background:'#fff',borderRadius:10,maxWidth:900,width:'95%',padding:16}}><div style={{display:'flex',gap:12}}><div style={{flex:1}}><img src={hamper.img} style={{width:'100%',height:340,objectFit:'cover',borderRadius:8}}/></div><div style={{flex:1}}><h3>{hamper.title}</h3><p style={{color:'#666'}}>{hamper.price}</p><p>Includes festive decor items and lights.</p><div style={{marginTop:12}}><button onClick={()=>onOrder(hamper)} style={{background:'#B30000',color:'#fff',padding:'8px 12px',borderRadius:6}}>Order Now</button><button onClick={()=>onEnquiry(hamper)} style={{marginLeft:8,padding:'8px 12px',borderRadius:6}}>Enquire</button></div></div></div></div></div>)}export default function Home(){const [open,setOpen]=useState(null);const [orderHamper,setOrderHamper]=useState(null);const [enqHamper,setEnqHamper]=useState(null);const [thank,setThank]=useState(null);
  function handleOrderSubmit(e){e.preventDefault();setThank('order');setOpen(null)}
  function handleEnquirySubmit(e){e.preventDefault();setThank('enquiry');setOpen(null)}
  return (<div><section style={{height:360,backgroundImage:"url('/src/assets/hero-hampers.webp')",backgroundSize:'cover',backgroundPosition:'center',display:'flex',alignItems:'center',justifyContent:'center'}}><div style={{background:'rgba(0,0,0,0.35)',padding:20,borderRadius:8,color:'#fff',textAlign:'center'}}><h1 style={{fontSize:32}}>Celebrate Christmas, Beautifully</h1><p>Premium festive hampers for homes & offices</p><a href='#hampers' style={{background:'#B30000',color:'#fff',padding:'8px 12px',borderRadius:6}}>See Hampers</a></div></section><section id='hampers' style={{padding:32}}><div style={{maxWidth:1100,margin:'0 auto'}}><h2>Our Hampers</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:16,marginTop:16}}>{H.map(h=>(<div key={h.id} style={{background:'#fff',padding:12,borderRadius:8,boxShadow:'0 8px 20px rgba(0,0,0,0.06)'}}><img src={h.img} style={{width:'100%',height:180,objectFit:'cover',borderRadius:6}}/><h3 style={{marginTop:8}}>{h.title}</h3><p style={{color:'#666'}}>{h.price}</p><div style={{marginTop:8}}><button onClick={()=>setOpen(h)} style={{background:'#B30000',color:'#fff',padding:'8px 12px',borderRadius:6}}>View Details</button></div></div>))}</div></div></section>
  {/* hidden netlify forms */}
  <div style={{display:'none'}}><form name='order-form' method='POST' data-netlify='true' action='/thank-you-order'><input type='hidden' name='form-name' value='order-form'/><input name='hamper'/><input name='name'/><input name='phone'/><input name='email'/><input name='address'/><input name='quantity'/></form>
  <form name='enquiry-form' method='POST' data-netlify='true' action='/thank-you-enquiry'><input type='hidden' name='form-name' value='enquiry-form'/><input name='hamper'/><input name='name'/><input name='phone'/><input name='email'/><input name='company'/><input name='quantity'/><textarea name='message'></textarea></form></div>
  <Modal open={!!open} onClose={()=>setOpen(null)} hamper={open||H[0]} onOrder={(h)=>{setOrderHamper(h);document.getElementById('order-trigger')?.click()}} onEnquiry={(h)=>{setEnqHamper(h);document.getElementById('enquiry-trigger')?.click()}} />
  {/* visible triggers that open small modals for forms */}
  <div id='order-modal' style={{display:'none'}}></div>
  {/* thank you */}
  {thank && (<div style={{position:'fixed',inset:0,display:'flex',alignItems:'center',justifyContent:'center',background:'rgba(0,0,0,0.5)'}} onClick={()=>setThank(null)}><div style={{background:'#fff',padding:20,borderRadius:8}}><h3>{thank==='order'?'Thanks for your order!':'Thanks for your enquiry!'}</h3><p>We will contact you within 2 hours.</p><button onClick={()=>setThank(null)} style={{marginTop:12,background:'#B30000',color:'#fff',padding:'8px 12px',borderRadius:6}}>Close</button></div></div>)}
  </div>)}